[project]
name = "bar-banker-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adafruit-circuitpython-pn532>=2.4.6",
    "erlang-py>=2.0.7",
    "gpiozero>=2.0.1",
]
